### PR TITLE
Release 5.0.1

### PR DESCRIPTION
**Pull request by rjuju**

### CODE REVIEW

**Review by pgiraud — APPROVED** [review]

**Comment by rjuju** [comment]
Marking as draft to avoid merging it until the MANIFEST.in thing is resolved.

**Comment by rjuju** [comment]
@pgiraud just to be sure that everything is ok for releasing 5.0.1

**Review by pgiraud — APPROVED** [review]

**Comment by pgiraud** [comment]
@rjuju what do you think about yanking version 5.0.0 in Pypi?

**Comment by rjuju** [comment]
good idea, done!

**Pull request merged**
