### PR TITLE
V5 compatibility with Node 22

### LINKED ISSUE #195: v5 is not compatible with node 22
Trying to start the vite server fails with:

```bash
$ npm run dev

> powa@0.1.0 dev
> vite

failed to load config from /home/rjuju/git/powa/powa-web/vite.config.js
error when starting dev server:
SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:18)
    at callTranslator (node:internal/modules/esm/loader:430:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:436:30)
```

That seems to be a problem introduced with node 22.

### PR DESCRIPTION
**Pull request by pgiraud**
FIxes #195

### CODE REVIEW

**Comment by rjuju** [comment]
thanks a lot for taking care of that! I will do some testing, but just to be sure is it supposed to be compatible with node 21- too?

**Comment by pgiraud** [comment]
Apparently it does for node 16, 18, 20. I'm using `nvm` to easily switch from one version of `npm` to another.

I didn't test thouroughly though but the server starts with no error message.

**Comment by rjuju** [comment]
that's good enough for me 😊

**Review by rjuju — APPROVED** [review]
LGTM!

**Pull request merged**
