### PR TITLE
fixup! Remove sqlalchemy dependency.

### PR DESCRIPTION
**Pull request by pgiraud**
I added a fixup commit for the removal of SQLAlchemy dependency.

### CODE REVIEW

**Comment by rjuju** [comment]
Ah thanks, I was sure I tested this code path.  Should I merge this PR / rebase / push force or do you want to put this patch at the begining of your big PR?  Getting rid of sqlalchemy wasn't a particularly simple commit so I wouldn't be surprised if you found more similar problems.

**Comment by pgiraud** [comment]
Let's add it directly to the v5 branch. Can you do the merge, then fixup and push force?

**Comment by rjuju** [comment]
Sure!

**Comment by rjuju** [comment]
It should be ok now, thanks for the fix!

**Pull request merged**
